# Generated by Django 3.0.3 on 2020-06-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_news_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('True', 'Evet'), ('New', 'Yeni'), ('False', 'Hayır')], default='New', max_length=10),
        ),
    ]
