# Generated by Django 3.0.3 on 2020-05-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200515_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
